### ISSUE TITLE
'@nodejs/development' not installable in workshop environment

### ISSUE THREAD

**Issue by bmarlow** [ansible/workshop-examples#4]
Specifically:
In  workshop-examples/rhel/webops/web_infrastructure.yml (in the webops branch) 
 - name: install nodejs
    dnf:
      name: '@nodejs/development'
      state: present

The job that calls this fails because the brotli-devel package is not available for installation as none of the enabled repo's have it.

**Comment by ffirg** [comment]
snap, same issue encountered today in a couple of workshops as well.

**Comment by aal001** [comment]
Package brotli-devel missing from the RHEL8 base repo.
There is a ticket on https://access.redhat.com/solutions/4479281 (yet to be verified by RH support) that the brotli-devel package is available on the codeready-builder-for-rhel-8-x86_64-rpms repo. 

A temporary workaround is to install the missing package from a CentOS repo: http://mirror.centos.org/centos/8/PowerTools/x86_64/os/Packages/brotli-devel-1.0.6-1.el8.x86_64.rpm 
That solved it for me.

**Comment by IPvSean** [comment]
is this still an issue?

**Comment by bmarlow** [comment]
No.  Looks like that might have been a transient issue.

brotli-devel is now included in the AppStream repo all the way to 8.0
